'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import CustomTextField from 'src/components/text-field'
import { useTheme } from '@mui/material'
import { useSettings } from 'src/hooks/useSettings'

export default function Home() {
  const theme = useTheme()
  const { settings } = useSettings()

  return (
    <>
      <Head>
        <title>Next-Ecomerce</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Button variant='contained'>Hello world updated</Button>
      <CustomTextField
        sx={{
          width: '300px',
          margin: '40px'
        }}
        id='outlined-multiline-flexible'
        defaultValue='Default Value'
      />
    </>
  )
}
